[[manager.prepend_keymap]]
on = [ "u", "a" ]
exec = "plugin bookmarks-persistence --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "u", "g" ]
exec = "plugin bookmarks-persistence --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "u", "d" ]
exec = "plugin bookmarks-persistence --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "u", "D" ]
exec = "plugin bookmarks-persistence --args=delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = ["g", "l" ]
exec = "shell --block lazygit --confirm"
desc = "Open lazygit"
